bufbuild/buf-action

Makefile, README.md, action.yml, dist/index.js, examples/version-input.yaml, src/installer.ts
Runs `VERSION=0.1.0 make updateversion` to update the docs and CI with the latest version of buf `1.32.2`. Removes two TODOS. Fixes an action setting for archive which is safe to enable and sets the min version to `v1.32.0`.
=> Update buf version 1.32.2

action.yml
I don't think we need an example here (don't want to hard code a specific version that will either get out of date or that we will need to update with each release), and updated the docs to clarify that download will only happen if necessary.
=> Update version docs

.github/workflows/ci.yaml, dist/index.js, src/main.ts
Have an error report of: `Error: Cannot read properties of undefined (reading 'status')`. I believe it's from the `steps[key].status == Status.Failed` if the value is in the object but undefined. Removed the class for an object that is allowed to be partial and added more `?.` guards for field access.
=> Fix undefined steps for partial workflow

README.md, RELEASE.md, examples/buf-ci.yaml, examples/only-checks.yaml, examples/only-setup-defaults.yaml, examples/only-setup.yaml, examples/only-sync.yaml, examples/push-on-changes.yaml, examples/skip-on-commits.yaml, examples/skip-on-labels.yaml, examples/validate-push.yaml, examples/version-env.yaml, examples/version-file.yaml, examples/version-input.yaml, examples/version-latest.yaml
Add RELEASE.md to document the release workflow. Follows the guide in prep for v0.1.1. 
To publish this release will create the tags `v0` and `v0.1` in addition to the current release `v0.1.1`.
=> Prepare for v0.1.1

.github/workflows/ci.yaml, Makefile, eslint.config.mjs, package-lock.json, package.json
The license-header binary is also available as a npm binary. It integrates nicely into npm projects because it's installed as a npm dependency, supports configuration in package.json, idiomatic glob ignores, and several additional typical file extensions.
Since this is a npm project, it makes sense to me to use it here.
=> Switch to npm binary for license headers

.github/workflows/ci.yaml, action.yml
Fix invalid use of `github.ref_name` which points to `main` and not the pull request branch on `delete` events. We now correctly set the label as `github.event.ref_name` which points to the branch.
=> Fix default archive commands for PRs

README.md, examples/buf-ci.yaml, examples/only-checks.yaml, examples/only-setup-defaults.yaml, examples/only-setup.yaml, examples/only-sync.yaml, examples/push-on-changes.yaml, examples/skip-on-commits.yaml, examples/skip-on-labels.yaml, examples/validate-push.yaml, examples/version-env.yaml, examples/version-input.yaml, examples/version-latest.yaml
Whats changed:
- Fix default archive label in #10 
- Drop support for `.bufversion` files in #8 
Removed support for `.bufversion` files is a breaking change but is not currently used by known implementations.
=> Prepare for v0.1.2

.github/workflows/ci.yaml, action.yml, dist/index.js, src/main.ts
This PR fixes two issues with the archive step. First is a typo in the default event name of `archive_labels`. This should be `github.event.ref` not `github.event.ref_name. The other fix is for more robust handling of multiple non existent labels. For `delete` events we cannot guarantee the branch or tag is matched to a label in the BSR. We now iterate over all labels and handle missing failures.
=> Fix archive for non-existent labels

README.md, examples/push-on-changes.yaml
This PR adds a new section for linking to the push on changes example, which was a requested example. I've also re-ordered the README.md to move the `Customizing Behaviour` section below the `Version` and `Authentication` sections. I think this reads better for the user, as the user will generally want to customize the `Version` and `Authentication` before customizing the defaults, which is a more advanced use case.
=> Improve links to example workflows

README.md, examples/disable-skip/buf-ci.yaml
This PR showcases a workflow to disable label skips which are on by default. To disable, we override the default input removing the checks against the label.
=> Add example to disable label skips

.github/workflows/ci.yaml, action.yml, dist/index.js, package-lock.json, package.json, src/config.ts, src/installer.ts, src/main.ts, src/outputs.ts
This PR allows for better push behaviour when unnamed modules are present. The action will now read the `buf.yaml` config file to check for missing names before running the push or archive steps. With the latest release of `buf`@v.1.33.0 we can now also use the flag `--exclude-unnamed` to avoid failing push on unnamed modules when multiple modules are present. 
As a test (and example) see the [`test-push-unnamed`](https://github.com/bufbuild/buf-action/actions/runs/9503406199/job/26193768827?pr=31) step in CI:
```
/opt/hostedtoolcache/buf/1.33.0/x64/buf push --error-format github-actions --exclude-unnamed --create --git-metadata
WARN	Excluding unnamed module	{"module": "bar"}
buf.build/***/foo:2969b75dd86b4895a5e590dc1bb89
```
In addition is the introduction of outputs in the `action.yml` …
=> Fix push with no configured module names

.github/workflows/ci.yaml, Makefile, README.md, action.yml, dist/index.js, examples/version-input/buf-ci.yaml, src/installer.ts
Set the min supported version of buf to v1.34.0. This pulls in the required change https://github.com/bufbuild/buf/pull/3103 for better compatibility with different environments.
=> Require buf v1.34.0

.github/workflows/ci.yaml, dist/index.js, src/main.ts
It's confusing to not show the check was skipped, this is preferred over not showing the value if the user explicitly disables it via the input parameter.
=> Include skipped checks in summary

.github/workflows/ci.yaml, dist/index.js, package-lock.json, package.json, src/comment.ts, src/main.ts
Update summary comments to better display the status of the checks by including an error count, link to the run, and a last updated time. Update time is useful to ensure that the run reflects the expected results. The format check has been updated to convert `diff` output to GitHub annotations. Table is formatted horizontally to aid readability. There are also links to the BSR for push and archive events.
=> Improve summary comments

dist/index.js, src/inputs.ts, src/main.ts
Dependabot doesn't have access to repository secrets failing to run workflows when automatically run. We can easily check in the action for the actor [`dependabot[bot]`](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events) to skip these cases. This avoids users having to configure the action themselves.
=> Skip when dependabot[bot] actor

.github/workflows/ci.yaml, README.md, action.yml, dist/index.js, src/comment.ts, src/main.ts
The action may be run multiple times as requested. This isn't supported by the PR comment status update as it presumes a single run of a v2 style workspace. To support this case we now dedupe comments on workflow and job name. The `view` link is moved to a `<workflow> / <job> (pull_request)` link in the comment description to help users differentiate runs. The name matches the status name below the CI fold. Note: there is no step level ID provided to the action so each invocation must be unique combination of workflow and job name otherwise the comment will update a previous comment.
Fixes #51
=> Support duplicate action comments on PRs

dist/index.js, src/comment.ts
For a better migration story ensure the old style comment tags are captured to avoid stale comments on PRs. The action will now convert the comments from the previous style to the new comment tag. This may cause temporary failures for comments with multiple runs, but those cases just need to be re-run to correct the state.
=> Fix new comment tags to overwrite old comments

README.md, action.yml
Forked PRs can fail to access the secrets for the repository. This can fail on trying to comment the results from CI on the PR. Disable comments for all forked by default.
Tested here on a forked https://github.com/emcfarlane/releases/pull/14 and unforked https://github.com/emcfarlane/releases/pull/15 change. The update before reference buf-action@main, then updating to buf-action@ed/disableForkComment the forked comment now disables the comment, whilst the unforked still comments.
=> Disable PR comment by default from forks

package-lock.json, package.json
Releases the changes in https://github.com/bufbuild/buf-action/pull/64 to fix failures in CI for contributors PRs.
=> Prepare for v1.0.1

.github/workflows/ci.yaml, README.md, dist/index.js, src/main.ts
To provide better errors we can map some of the buf errors to config issue errors. It's easy to miss the `- uses: actions/checkout@v4`  step, provide an annotation to help resolve issues. This adds an info log:
```diff
/opt/hostedtoolcache/buf/1.35.0/x64/buf build --error-format github-actions
Failure: "." had no .proto files
+Did you forget to add the "actions/checkout@v4" checkout step to your workflow?
Error: Failed build
```
=> Check input for empty directories

dist/index.js, src/installer.ts
This avoids requiring the version of Buf found in the PATH to match the resolved. Fallback to installing a new explicit version in the toolcache.
Fixes #71
=> Allow overriding Buf version in PATH

MIGRATION.md, README.md
Improve the documentation for migrating from the individual actions.
=> Add migration guide doc

README.md, dist/index.js, src/main.ts
Inherits the debug condition from the action to enable running of commands with `--debug` flag set. This is preferred over an explicit `debug` parameter to avoid churn in changing the config. 
Closes #77
=> Set debug when the action is using debug logging

dist/index.js, src/main.ts
This ensures push will work on enterprise GitHub instances that have arbitrary URLs.
=> Set --source-control-url on push

.github/workflows/ci.yaml
This was removed before 1.0, causing warning in test output.
=> Cleanup removed action input username

.github/workflows/dependabot.yaml
To allow dependabot to upgrade deps, run an action to rebuild after the package updates. Based on https://github.com/dependabot/dependabot-core/issues/5962#issuecomment-1303781931
=> Rebuild on dependabot updates

package-lock.json, package.json
Below is the draft release notes:
* Add migration guide doc by @emcfarlane in https://github.com/bufbuild/buf-action/pull/74
* Set --debug when the action is using debug logging by @emcfarlane in https://github.com/bufbuild/buf-action/pull/78
* Set --source-control-url on push so that the push action now works by default on enterprise GitHub instances by @nicksnyder in https://github.com/bufbuild/buf-action/pull/86
* @doriable made their first contribution in https://github.com/bufbuild/buf-action/pull/98
**Full Changelog**: https://github.com/bufbuild/buf-action/compare/v1.0.2...v1.0.3
=> Prepare for v1.0.3

.github/workflows/ci.yaml
Skips testing of comments for dependabot. The action will skip writing of comments when the dependabot actor is detected.
=> Fix CI comment test for dependabot

action.yml, dist/index.js, dist/post/index.js, src/inputs.ts, src/installer.ts, src/main.ts
This fixes the version resolution on enterprise instances by ensuing the API call is always resolved to the public GitHub instance.
Fixes #129
=> Fix latest version resolution for GitHub enterprise

package-lock.json, package.json
Below is the draft release notes:
This release improves support for running the action for GitHub enterprise users. It adds a new parameter `public_github_token` for authentication with the public GitHub. This fixes version resolution and authenticates downloads  for enterprise instances.
* Add post step to run logout by @emcfarlane in https://github.com/bufbuild/buf-action/pull/105
* Fix latest version resolution for GitHub enterprise by @emcfarlane in https://github.com/bufbuild/buf-action/pull/131
**Full Changelog**: https://github.com/bufbuild/buf-action/compare/v1.0.3...v1.1.0
=> Prepare for v1.1.0

dist/index.js, src/installer.ts, src/main.ts
This fixes enterprise use of the action when not specifying the parameter `public_github_token`. If the version resolution is not required the action does not need to build the GitHub API client. If it is needed an error explaining the issue is now returned.
Closes #143
=> Fix GitHub enterprise without specifying public tokens

.github/workflows/ci.yaml, Makefile, action.yml, examples/version-input/buf-ci.yaml, package-lock.json, package.json
Release notes:
* Fix GitHub enterprise use of optional `public_github_token` parameter by @emcfarlane in https://github.com/bufbuild/buf-action/pull/144
**Full Changelog**: https://github.com/bufbuild/buf-action/compare/v1.1.0...v1.1.1
=> Prepare for v1.1.1

.github/workflows/ci.yaml, README.md, action.yml, dist/index.js, dist/post/index.js, examples/version-input/buf-ci.yaml, src/inputs.ts, src/installer.ts, src/main.ts
This PR adds a new parameter `checksum` to the GitHub action input to validate the sha256 hash of the installed buf binary.
Closes #168
=> Add checksum to verify binary

dist/index.js, src/installer.ts
This fixes windows install compatibility by changing `exec` to use `fs.promise` on setting file permissions.
=> Fix windows install chmod

.github/workflows/ci.yaml, README.md, action.yml, dist/index.js, dist/post/index.js, src/inputs.ts, src/installer.ts, src/main.ts
This PR adds a new parameter `breaking_against_registry` which enables setting the new buf flag [--breaking-against-registry](https://buf.build/docs/reference/cli/buf/breaking/#against-registry). If the flag  is set, the version of buf is required to be `>=1.51.0` to when the feature was introduced. This avoids requiring the min version changed.
=> Add breaking against registry parameter

dist/index.js, src/main.ts
This PR limits the message of push and archive steps to only the passing state. These messages are only set on a pull request so are not normally visible.
=> Fix push and archive status message on non-passed results

README.md
Updates the README ([tl;dr link to view the new version](https://github.com/bufbuild/buf-action/tree/jrinehart/docs-consolidation)) to remove documentation that's been incorporated into buf.build/docs.
=> Removing README content that's moved to Buf docs

.github/workflows/ci.yaml, action.yml, dist/index.js, dist/post/index.js, examples/push-create-public/buf-ci.yaml, src/inputs.ts, src/main.ts
This adds the parameter `push_create_visibility` to allow setting the visibility to public on creation of new modules with buf push. 
Fixes https://github.com/bufbuild/buf-action/issues/150
=> Add push_create_visibility parameter
