examples/only-checks.yaml, examples/only-setup-defaults.yaml, examples/only-setup.yaml, examples/only-sync.yaml, examples/push-on-changes.yaml, examples/skip-on-commits.yaml, examples/skip-on-labels.yaml, examples/validate-push.yaml, examples/version-env.yaml, examples/version-input.yaml, examples/version-latest.yaml
Enforce the naming convention of the file matching the name prefix. This gives each example a unique name with the recommended approach (`buf-ci.yaml`) being the recommended workflow as in the README.md with `name: Buf CI`.
=> Correct example names

.github/workflows/ci.yaml
Covers a missing testcase of push with a token but without providing a username for login. Checks credentials are still passed.
=> Add test on push for token only auth

README.md, RELEASE.md, examples/buf-ci.yaml, examples/only-checks.yaml, examples/only-setup-defaults.yaml, examples/only-setup.yaml, examples/only-sync.yaml, examples/push-on-changes.yaml, examples/skip-on-commits.yaml, examples/skip-on-labels.yaml, examples/validate-push.yaml, examples/version-env.yaml, examples/version-input.yaml, examples/version-latest.yaml
Release fix for archive commands.
=> Prepare for v0.1.3

.github/workflows/ci.yaml, action.yml
Use the GitHub script action to test the comment for integration testing. We now edit the comment to notify the author and reviewers that this is a test comment and mark the comment as resolved when completed.
=> Improve test of comment

action.yml, examples/README.md
=> Documentation updates

dist/index.js, src/comment.ts, src/inputs.ts, src/installer.ts, src/main.ts
Add documentation to types and functions for code readability.
=> Document types and function declarations

README.md
It is kind of jarring and shouldn't be necessary.
=> Remove notice

action.yml
Max length for a description is 125 characters. Proposed text is 118.
=> Shorter description

package-lock.json
=> Upgrade braces

Makefile, README.md, action.yml, examples/disable-skip/buf-ci.yaml, examples/version-input/buf-ci.yaml, package.json
Update version in preparation for release.
=> Prepare for v0.1.4

dist/index.js, src/main.ts
Logs skipping the step is potentially confusing for users, switch to debug logs.
=> Quiet skip logs

README.md
Add missing parameters from the action.yaml to the README.md
=> Document GitHub actor and token parameters

.github/workflows/ci.yaml, Makefile, README.md, action.yml, dist/index.js, examples/buf-ci.yaml, examples/disable-skip/buf-ci.yaml, examples/only-setup-defaults/buf-ci.yaml, examples/only-setup/buf-ci.yaml, examples/only-sync/buf-ci.yaml, examples/push-on-changes/buf-ci.yaml, examples/skip-on-commits/buf-ci.yaml, examples/skip-on-labels/buf-ci.yaml, examples/validate-push/buf-ci.yaml, examples/version-input/buf-ci.yaml, src/inputs.ts, src/installer.ts, src/main.ts
No longer required by `buf` as of `v1.35.0`, requires version restriction.
=> Drop username config

README.md, examples/buf-ci.yaml, examples/disable-skip/buf-ci.yaml, examples/only-checks/buf-ci.yaml, examples/only-setup-defaults/buf-ci.yaml, examples/only-setup/buf-ci.yaml, examples/only-sync/buf-ci.yaml, examples/push-on-changes/buf-ci.yaml, examples/skip-on-commits/buf-ci.yaml, examples/skip-on-labels/buf-ci.yaml, examples/validate-push/buf-ci.yaml, examples/version-env/buf-ci.yaml, examples/version-input/buf-ci.yaml, examples/version-latest/buf-ci.yaml, package-lock.json, package.json
This is `buf-action`'s first release! It does not contain any user-facing changes from v0.3.0.
=> Prepare for v1.0.0

examples/only-setup-defaults/buf-ci.yaml, examples/skip-on-commits/buf-ci.yaml, examples/skip-on-labels/buf-ci.yaml
=> Fix examples syntax

examples/check-before-push/buf-ci.yaml
Provides an example to guard pushes based on checks.
Fixes #67
=> Add example for checks to guard push

RELEASE.md, package-lock.json, package.json
Prepare a new release to add fix for #72 .
=> Prepare for v1.0.2

LICENSE, dist/index.js, eslint.config.mjs, package.json, src/comment.ts, src/config.ts, src/inputs.ts, src/installer.ts, src/main.ts, src/outputs.ts
Update license year range to include 2025.
=> Update license year range

.github/dependabot.yml
This adds dependabot config to ensure the action deps are maintained.
=> Add dependabot config for NPM packages

dist/index.js, package-lock.json, package.json, src/main.ts
Run the migration, fixed the package lock file dependencies.
=> Upgrade connect to v2

dist/index.js, package-lock.json
=> Upgrade packages

README.md, examples/enterprise/buf-ci.yaml
Adds an example for GitHub enterprise and missing parameter in the README.
=> Improve docs for GitHub enterprise

dist/index.js, dist/post/index.js, package-lock.json, package.json
=> Upgrade deps

package-lock.json, package.json
Below is the draft release notes:
* Add optional checksum parameter to verify binary by @emcfarlane in https://github.com/bufbuild/buf-action/pull/169
**Full Changelog**: https://github.com/bufbuild/buf-action/compare/v1.1.1...v1.1.2
=> Prepare for v1.1.2

dist/index.js, package-lock.json, package.json, src/installer.ts
This replaces use of 'which' with exec for @actions/io package.
=> Use actions/io package for which

package-lock.json, package.json
Below are the draft release notes:
* Fix windows install by using @actions/io package for cross platform `which` command by @emcfarlane in https://github.com/bufbuild/buf-action/pull/175
**Full Changelog**: https://github.com/bufbuild/buf-action/compare/v1.1.2...v1.1.3
=> Prepare for v1.1.3

package-lock.json, package.json
Below are the draft release notes:
* Fix windows install use of chmod by @emcfarlane in https://github.com/bufbuild/buf-action/pull/177
**Full Changelog**: https://github.com/bufbuild/buf-action/compare/v1.1.3...v1.1.4
=> Prepare for v1.1.4
